name: Maven Tests

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven tests
        run: mvn clean test || echo "Tests failed, proceeding to report generation"

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install unzip wget -y

      - name: Install Allure
        run: |
          echo "Downloading Allure..."
          # Fetch the latest Allure release download link
          ALLURE_VERSION=$(wget -qO- "https://api.github.com/repos/allure-framework/allure2/releases/latest" | grep -oP '"tag_name": "\K(.*)(?=")') || { echo "Failed to fetch the latest Allure version"; exit 1; }
          ALLURE_URL="https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip"
          echo "Downloading Allure from: ${ALLURE_URL}"
          wget -qO allure.zip "${ALLURE_URL}" || { echo "Failed to download Allure"; exit 1; }

          # Check if the file exists and is not empty
          if [[ -s allure.zip ]]; then
              echo "Unzipping Allure..."
              unzip allure.zip -d /opt || { echo "Failed to unzip Allure"; exit 1; }
              echo "Creating symlink for Allure..."
              sudo ln -s /opt/allure-${ALLURE_VERSION}/bin/allure /usr/bin/allure || { echo "Failed to create symlink"; exit 1; }
          else
              echo "Allure download failed or the file is empty."
              exit 1
          fi

      - name: Generate Allure report
        run: allure generate target/allure-results --clean -o allure-report || { echo "Failed to generate Allure report"; exit 1; }

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
